[package]
name = "payload_ransomware"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
walkdir = "2.3"
chacha20poly1305 = "0.10"
rand = "0.8"
rayon = "1.7"
